### ISSUE TITLE
Trading Api  Incorrect content digest of sha-256 to fulfill the request.

### ISSUE THREAD

**Issue by romeolandry** [eBay/digital-signature-php-sdk#10]
Hey I try to make GetAccount call with the Digital Signature.

`<GetAccountResponse 
xmlns="urn:ebay:apis:eBLBaseComponents">
    <Timestamp>2022-12-29T11:17:20.527Z</Timestamp>
    <Ack>Failure</Ack>
    <Errors>
        <ShortMessage>Incorrect content digest of sha-256</ShortMessage>
        <LongMessage>Incorrect content digest of sha-256 to fulfill the request.</LongMessage>
        <ErrorCode>215105</ErrorCode>
        <SeverityCode>Error</SeverityCode>
        <ErrorClassification>RequestError</ErrorClassification>
    </Errors>
    <Version>1201</Version>
    <Build>E1201_CORE_API6_19110890_R1</Build>
</GetAccountResponse>`

my signed Header look like 

` array:13 [
  "Content-Type" => "text/xml"
  "Content-Length" => 2870
  "X-EBAY-API-COMPATIBILITY-LEVEL" => "1285"
  "X-EBAY-API-CALL-NAME" => "GetAccount"
  "X-EBAY-API-SITEID" => "77"
  "X-EBAY-API-APP-NAME" => "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  "X-EBAY-API-CERT-NAME" => "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  "X-EBAY-API-DEV-NAME" => "XXXXXXXXXXXXXXXXXXXXXXX"
  "Content-Digest" => "sha-256=:DlY4poPnCVmwpRtaYzS2r05/sqEaiO/XhicvPwcHsF4=:"
  "x-ebay-signature-key" =>"XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  "x-ebay-enforce-signature" => "true"
]
`
and the Body 

`<?xml version="1.0" encoding="UTF-8"?>
<GetAccountRequest xmlns="urn:ebay:apis:eBLBaseComponents">
    <RequesterCredentials xmlns="urn:ebay:apis:eBLBaseComponents">
        <eBayAuthToken>XXXXXXXXXXXXXXXXXXXXXXXXXXXXX</eBayAuthToken>
    </RequesterCredentials>
    <BeginDate>2022-12-19T11:17:20.000Z</BeginDate>
    <EndDate>2022-12-29T11:17:20.000Z</EndDate>
</GetAccountRequest>`

making the same call with this [php-sdk](https://github.com/sergo920/ebay-sdk-php).

`POST https://api.ebay.com/ws/api.dll` resulted in a `403 Forbidden` response:\n<GetAccountResponse \nxmlns=\"urn:ebay:apis:eBLBaseComponents\">\n<Timestamp>2022-12-29T11:40:22.592Z</Timestamp>\n<Ack>Failu (truncated...)\n`

**Comment by uherberg** [comment]
Hi @romeolandry 
Have you verified that the content digest is correct? You can copy&paste the payload into an online calculator for SHA-256 (or use the command line on Linux/Mac).
I am not sure about the 403 response; can you file a ticket on the developer portal? That way, we can track it, and I can work with the developer ecosystem team to investigate this.

**Comment by romeolandry** [comment]
Hi @uherberg,

thanks for your answer, 
I check the SHA-256 online and I can say if ist correct or not. 

the result of my content digest using you [this function(generateContentDigest)](https://github.com/eBay/digital-signature-php-sdk/blob/main/src/DigitalSignature/SignatureService.php) is :


**Body**

`<?xml version="1.0" encoding="UTF-8"?>
<GetAccountRequest xmlns="urn:ebay:apis:eBLBaseComponents"><RequesterCredentials xmlns="urn:ebay:apis:eBLBaseComponents"><eBayAuthToken>dumy token v^1.1#i^1#r^0#I^3#p^3#f^0#t^H4sIAAAAAAAAAOVZf2wbVx2v86MolIIQFaAOTZ4HEyWc/c539vlOtScndhI3jePESSGRaPru7r34Jee76727NM6YiAKqEEOgVRtDZYyu24SAToAQnZAY1fjxz4C2o0OrNok/gCEoZWLA1AIS4t3lR52gpbU9qZY4WbLu3ffn5/v9vvt+34HlnT0fOT50/Nru0Ns6Ti2D5Y5QiN8FenZ2976zs2Nv9w5QRxA6tfzB5a6Vzj/up7Bq2Mo4orZlUhRerBomVYLFdMRzTMWClFDFhFVEFVdTytmRg0o8ChTbsVxLs4xIuJBLR7CMgQ5SekpVpYSYhGzVXJc5YaUjSMRxCfCimNCQAFSRPafUQwWTutB005E4iAsc4DkgTvAJhf2ERFSQ+elI+BByKLFMRhIFkUxgrhLwOnW2bm8qpBQ5LhMSyRSyA+XRbCGXL07sj9XJyqzhUHah69HNd/2WjsKHoOGh7dXQgFope5qGKI3EMqsaNgtVsuvGNGF+AHUKYQglXpKTECRFKf6WQDlgOVXobm+Hv0J0DgekCjJd4tZuhihDQ51Dmrt2V2QiCrmw/zfmQYNggpx0JN+XnZos58cj4XKp5FgLREe67ykviIIgplJCJOMiyiBEzoxF56HDzRNTR44BTX1N56rgNcS3KO23TJ34+NFw0XL7EHMAbYUJ1MHEiEbNUSeLXd+4ejppHc6UMO3HdzWgnlsx/RCjKsMkHNzePBjr2XEjH96q/JAlgFKChnAKIiwm1/LDr/XWciTjhylbKsV8W5AKa1wVOvPItQ2oIU5j8HpV5BCdycJxIYURpydlzIkyxpya0JMcjxECCKmqJqf+T1PFdR2iei7aSJetDwJ/05GyZtmoZBlEq0W2kgQ70VpyLNJ0pOK6thKLHTt2LHpMiFrObCwOAB/7+MjBslZBVbYVr9OSmxNzJEgRDTEuShS3ZjNrFlkWMuXmbCQjOHoJOm6tz6ux+zIyDPa3nsmbLMxsXX0TV/sNwnCYYIray9Mhi7pIb8k1VpTQvQ1e+bW+jWd1aQpSQToLUQAkDkgKAC05nLXtQrXquVA1UEFvr3gmQUKOt+Sdv+cpBGLFteaR2X4ZO54fGM+Xh2YmRofzxZY8HUfYQbQy4fvZbnHMjmVzWXaN5A9mF8iIUxjK9U8VcQLLlYU57DmF4ep839jHQL+XPyCpgwdGR4fJcCl2YCEnjOeGxop8b2pR7RuePJpNp1sCqYw0B92O8t4ETvBe3wTQsDyfH8SDS7V5HU3FzFKvROMxdYkvGeWpETUpyblJo9g/PD1kFloDID/rkTZLDklPyBIWBD6VAFAS2bgR1wTAQ4xxggcq3/Lu1mb+jgYtzjDh+ISe4ETAIw6KAuZYN6SCFNJ0QRJb8tluuxDXcFVcmrOxU9Fa8oz6LVZ7uebzUyYA2iTqv2yimlWNWZANFP7SDPVr3bc6fDNCnyimejVmA+t9ow6CumUatVvnm/VYE73KfWtMlHWC0dV5gLnSoMbNzA3wEHOB9Y6WU2tG4QZzAzxQ0yzPdJtRt8baAAf2DEwMwx8TmlFYx96ImSY0ai7RaPMxDAZCBi8lsxW3UTlsjU2RjF+DLjSsRlPJT15asWzbz0KNTSoN1ArGrFagpwXDd2PGsjE0OA5p1tkNfrZLEMOX4td6S5LsimWilu2Bus46waaDuCHHP7VoWcjqAVtTtUBMf9+ljWwPbECP6g7EjVSPDWtBueqE2v6rpjF1DZA7iMmHt56pW5iaDYVpuQQTbVUG9VSqOcRuol7eVM6GYa0N3kgnDtLcGc8h7fWKX2/Y1s6kuOC+a6Wj/0YTx+mUgQCremuHDzm00G7dqqSjZDIp85ys8xInQkHjZC0Z5wQeC3JCVnUxKbfk8+05btnGYz4pxVNiQhBu+eRhy0LdQeH/HBfHNn+6yewILn4l9CxYCf2gIxQCEuD4XrBvZ+dkV+c7IpTtMVEKTV21FqME4ih7QZtsR3VQdB7VbEicjp0h8vKL2vW6j0anPgHev/HZqKeT31X3DQl84MaTbv5d79sdZ7MWEPkEnxAS0+DuG0+7+Pd27fnCH47+/Prle7K7lp4/8dB/PvvT3q4nnwK7N4hCoe4dXSuhHZOfGxv80K9OHPz1p/d1fO2xoT35Vx//0uD3xCPXrv0j9vvJ5x7+U/euK2BPOvlq+NLYL35y31d/+PC3MosPPbr0dE/u+YtH3n713dV9j2Sfsy9H3H13/Ln3Xqz86/E7X+g7/8hf9M93num9OHdFffbOr58+/Rq9H+8/efXi3h99954Ll5+6dOHDn5wr2t8M9T4x8M+LZ594qfqVw+hwUvzo60/GRl574OyFT/UcudrPjxaPPvMb+kbXF9O/feXexZMj0w/Sp59Zvk6O//I7A1Pn75/+zEudf/vyi3efOnn42/PvCV86/8q5u2a+8fe7pu84c+iw9caJf5++cub13AtzDtl77rFHvy+//GM9dd+532X/ajyYz5x9IOWVfnZlNYz/BfVwUN7OGwAA</eBayAuthToken></RequesterCredentials>
<AccountHistorySelection>BetweenSpecifiedDates</AccountHistorySelection>
<BeginDate>2022-12-25T11:15:57.000Z</BeginDate>
<EndDate>2022-12-30T11:15:57.000Z</EndDate>
<Pagination xmlns="urn:ebay:apis:eBLBaseComponents"><EntriesPerPage>20</EntriesPerPage>
<PageNumber>1</PageNumber></Pagination>
<IncludeNettedEntries>true</IncludeNettedEntries>
<IncludeConversionRate>true</IncludeConversionRate>
<AccountEntrySortType>AccountEntryCreatedTimeAscending</AccountEntrySortType>
<Currency>EUR</Currency></GetAccountRequest>`

**hash-256** `hash(str_replace('-', '', $cipher), $body, true)`

`^ b"""
¿d\x1A­├4¡Øâm╔ê┴ORÎ■2\x10.¨Ï
ödí\x1A\x05¢┼\x17Ý
"""`

**base64_encode**
`qGQa8MM0rZ2DbcmIwU9S1/4yEC752AqUZKEaBb3FF+0=`

**content digest**
sha-256=:qGQa8MM0rZ2DbcmIwU9S1/4yEC752AqUZKEaBb3FF+0=:

can you confirm if is correct or not?

all my the request with body didn't work because of it.

thanks for help.

**Comment by romeolandry** [comment]
I wont to close this Issue beacause I found a solution.

Using the api Explorer I play some test. the solution was:

- removing EbayCredential (token from Body) and into header as X-EBAY-API-IAF-TOKEN

 so now work well.
Thanks!
