### ISSUE TITLE
Installation error:  Could not find a version of package ebay/digital-signature-php-sdk matching your minimum-stability (stable).

### ISSUE THREAD

**Issue by romeolandry** [eBay/digital-signature-php-sdk#3]
I run the command `composer require ebay/digital-signature-php-sdk`  get the error:

In PackageDiscoveryTrait.php line 327:
                                                                                                                                                                                               
  Could not find a version of package ebay/digital-signature-php-sdk matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.  
                                                                                                                                                                                               
Environnement to reproduce:

- php 8.1
- Symfony 6.2

Please Help me. How can workarround?

**Comment by uherberg** [comment]
Hi @romeolandry 
Thanks for pointing this out. Can you try it again? I fixed the missing versioning in packagist; the current version is 1.0.1

**Comment by romeolandry** [comment]
thank it work well
