### ISSUE TITLE
Mismatch beetwen  SignatureConfig structure and Value from  Key Management API

### ISSUE THREAD

**Issue by romeolandry** [eBay/digital-signature-php-sdk#6]
Hello,

I implement Key [Management API](https://developer.ebay.com/api-docs/developer/key-management/overview.html) and get as response form createSigningKey sometthing like 
`{
    "signingKeyId": "1c46bf7e-70b4-4cab-afe8-4afd966e5841",
    "signingKeyCipher": "RSA",
    "publicKey": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxVt/nHh3J6//+jZyIwDZhj6MF0Aa47cIcLiNU8sOxP8dwyrGOWf4Y0BNbPzBgVGBsDZomPBVEv7hIOB6GUrhAlbFAknE1GPKd91fBlaS+I8l/OSa9AwD87gazqoYCjAdNq1I8RDnut3cxvsETl8vxk0IarJ6iqMOvRNVxwM485NXdTeW8nvlUnu8tMcVAWsyvFgfHCeKaYEig+PuR7HXix+kUHggWeaEvHMOidjRE0a4vSjPlGbGZgiH+bXDiMgunxMvOv8YR2FmJwPnZKIVSx37MHDY0n1hi4mG4m1K8FckxJTfMCegNnblSocetQN4yc8hB5JDyub9NmxUAOmLxwIDAQAB",
    "jwe": "eyJ6aXAiOiJERUYiLCJraWQiOiJiNmI4ZWY2MC0zODU4LTRiMGUtYTI5My1mZjQyOGJkZmMyZmMiLCJlbmMiOiJBMjU2R0NNIiwidGFnIjoiNzdheXRHLWxIYU1YeEhJdzlpZXdHQSIsImFsZyI6IkEyNTZHQ01LVyIsIml2IjoiZDZ2Z0NNUFZvZ1dGRW91TSJ9.L4DlgE2_9ebzubLqbSjI7BSH12N67skPLPftUDd74B8.I4ThJL2k5G_9FdRG.MArOG_4MIk1wQUccOKsMceTVNiRLFF8Rnn1v5f051A756svvJZxDSWTUuW6SeDCJ22K2UJcQcoaVXJdCXnAJO5ZDUEy8yCDVqeoJ3-vO3ZFd_RThcfl7KfLkTuJVE-U8ChBhBGnUG-YtMHmRia-AyS_Lwf4h6wcmYzhjxoc8F6n0dXaSsWZYaI31BdamxOF3uEuDyKWZWKyMiCdANouqpvf00dVOhEahFbzo0IPB9iTdERO9m-bzfaI-3Q_LzFilv2F5ZKf5vt4j1hPX4onyRnI-4XVfjs3Kr_PpMjzp0XWefApiBoWOR12g4RxsahnNW6hzt3Z-kb4Wj0X2VfT1jUP8yOiTuY5l0oTwApxxwXXJaKat03hDSO-YVM1tcIXXS7RcsYCOfAsoIvlkjVVcpzfNrVVe-sxZ_jO0ZTOw1c9lQbi3S9qKiFQtXANzGhpLlgHn7J6QHAGWl4ToqdS59MZhQ2Tx5fXLMqfcoRujXTET8LDBwGc8LM9maCbZNpkQxmmOD79yjAsIaYrKIzxptWe8RD39bBnxB3cKhZ6GQ1FRgJt2M133B-7TsOHsjnx-h8bUiYsjSzixHbKoa6L0j31fDDstosZ4.EfmlB0c4ZbtVhRVYcF6wIQ",
    "creationTime": 1670428940,
    "expirationTime": 1765036940
}`

and i don't receive the privateKey Fro the Api.

how cann I work aaround?
where should get the PrivateKey?

**Comment by uherberg** [comment]
@romeolandry I just tried this myself and can't reproduce this. Here is what I did:

```
curl --location --request POST 'https://apiz.ebay.com/developer/key_management/v1/signing_key' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer v^1.1#i^1#I^3#...' \
--data '{ "signingKeyCipher": "Ed25519" }'
```

And the response was:
```
{
    "signingKeyId": "14...",
    "signingKeyCipher": "ED25519",
    "publicKey": "M...",
    "privateKey": "M...",
    "jwe": "eyJ6a...",
    "creationTime": 1670432670,
    "expirationTime": 1765040670
}
```

**Comment by romeolandry** [comment]
I thanks! I  found my error.
