### ISSUE TITLE
Invalid SOAP headers once signed 

### ISSUE THREAD

**Issue by compadvance** [eBay/digital-signature-php-sdk#9]
Hi , 
When I sign ebay SOAP headers using this software ,Invalid SOAP header error appears , 
no problems without signature . 
that's my signed headers bellow , thanks for looking at it .
Emil

    ["namespace"]=>
    string(31) "urn:ebay:apis:eBLBaseComponents"
    ["name"]=>
    string(20) "RequesterCredentials"
    ["data"]=>
    array(6) {
      [0]=>
      object(SoapVar)#55 (2) {
        ["enc_type"]=>
        int(301)
        ["enc_value"]=>
        object(eBayAuth)#49 (2) {
          ["eBayAuthToken":"eBayAuth":private]=>
          object(SoapVar)#53 (3) {
            ["enc_type"]=>
            int(101)
            ["enc_value"]=>
            string(96) "xxxxxxxxxxxxxxxxxxcorrectxxxxxxxxxxxxxxx"
            ["enc_namens"]=>
            string(31) "urn:ebay:apis:eBLBaseComponents"
          }
          ["Credentials":"eBayAuth":private]=>
          object(SoapVar)#54 (3) {
            ["enc_type"]=>
            int(301)
            ["enc_value"]=>
            object(eBayCredentials)#48 (3) {
              ["AppId":"eBayCredentials":private]=>
              object(SoapVar)#50 (3) {
                ["enc_type"]=>
                int(101)
                ["enc_value"]=>
                string(36) "xxxxxxxxxxxxxxxxxxcorrectxxxxxxxxxxxxxxx"
                ["enc_namens"]=>
                string(31) "urn:ebay:apis:eBLBaseComponents"
              }
              ["DevId":"eBayCredentials":private]=>
              object(SoapVar)#51 (3) {
                ["enc_type"]=>
                int(101)
                ["enc_value"]=>
                string(36) "xxxxxxxxxxxxxxxxxxcorrectxxxxxxxxxxxxxxx"
                ["enc_namens"]=>
                string(31) "urn:ebay:apis:eBLBaseComponents"
              }
              ["AuthCert":"eBayCredentials":private]=>
              object(SoapVar)#52 (3) {
                ["enc_type"]=>
                int(101)
                ["enc_value"]=>
                string(36) "xxxxxxxxxxxxxxxxxxcorrectxxxxxxxxxxxxxxx"
                ["enc_namens"]=>
                string(31) "urn:ebay:apis:eBLBaseComponents"
              }
            }
            ["enc_namens"]=>
            string(31) "urn:ebay:apis:eBLBaseComponents"
          }
        }
      }
      ["Content-Digest"]=>
      string(54) "sha-256=:Xxxxxxxxxxxxxxxxxxxcorrectxxxxxxxxxxxxxxx"
      ["x-ebay-signature-key"]=>
      string(196) "xxxxxxxxxxxxxxxxxxcorrectxxxxxxxxxxxxxxx"
      ["Signature-Input"]=>
      string(83) "sig1=("content-digest" "x-ebay-signature-key" "@method" "@path");created=1670595431"
      ["Signature"]=>
      string(95) "sig1=:+-xxxxxxxxxxxxxxxxxxcorrectxxxxxxxxxxxxxxx"
      ["x-ebay-enforce-signature"]=>
      string(4) "true"
    }
    ["mustUnderstand"]=>
    bool(false)
  }
}

**Comment by uherberg** [comment]
Hi Emil,

I am currently on a leave this week, but will have a look next Monday. I
will also inform colleagues.

Thanks
Ulrich

**Comment by zislogic** [comment]
Hi Emil, we are looking into this issue and I will get back to you once we have news. Sorry for any inconvenience!

**Comment by uherberg** [comment]
@compadvance Sorry for the late response. I am currently out on a medical leave. 
Can you please post the URL, the request body and the exact response that you receive (status code, headers and body)

**Comment by compadvance** [comment]
Thats all resolved now ,

please close the thread

Kind Regards

Emil
Compadvance Ltd

**Comment by uherberg** [comment]
Great to hear that it works now!
